application: PROJECT
version: 1
runtime: go
api_version: go1
env_variables:
  KUBE_CA_CRYPTOKEY: projects/PROJECT/locations/LOCATION/keyRings/KEYRING_NAME/cryptoKeys/CRYPTOKEY_NAME
  KUBE_CA_AUTHKEY: AUTHENTICATION_KEY
  KUBE_CA_KEY: BASE64_ENCRYPTED_PRIVATE_KEY
  KUBE_CA_CERT: BASE64_CERTIFICATE

handlers:
- url: /.*
  script: _go_app
